== Personal configurations

This repository contains configurations of several of the tools that I use, and
that I try to share and have in sync with different machines. Sharing your
configurations (specially your vimrc file) on a public Git repository is quite
common, but I finally dared to do it thanks to a great Vim and Git promoter,
http://drewneil.com/[Drew Neil], who made a great
http://vimcasts.org/episodes/synchronizing-plugins-with-git-submodules-and-pathogen/[
screencast on keeping in sync your Vim configuration with Git and Github].

== Micro Vim plugins

Besides some little things in the `vimrc` file, I started putting some things
that eventually could grow to a plugin in it's own in the plugin directory. For
example, `foldcomments.vim` tries to imitate a feature that I've learnt to love
from http://www.qt.io/ide[Qt Creator]: fold the first comment of a file (because
it tipically is a copyright notice which might contain lots of repetitive
information from the same project). Look at them in `dotvim/plugin`.

I also have a Neovim-only "remote plugin" written in ruby, which allows to sort
lines based on a certain "header". Like when a list of items in Asciidoc needs
to get sorted alphabetically, but each entry spans more than one line. Or when
you want to sort some blocks of code of `switch`/`case` based only on the line
containing the `case` (and everything below it should be respected). A somewhat
valid alternative would be https://github.com/vim-scripts/AdvancedSorters[the
AdvancedSorters plugin], which is just VimL, but seems a mess to install, with
two dependencies for such a simple thing (and doesn't seem to be officially on
Github, Gitlab or any other project management system).

In other `dotvim` subdirectories there might be some personal or even common
sense settings. Or plain fixes to the lack of completeness of the file type
support in Vim. Blame the stupidity of the Vim development model for not sending
the changes upstream.

== Usage notes

=== Update dictionary files

I always keep forgetting how dictionaries work. The usual place where I find the
help is the http://vimcasts.org/episodes/spell-checking/[Vimcasts episode on
spell checking] and the linked article. However, the linked article mentions
dictionaries in `aff` and `dic` formats, while I just did:

[source,viml]
----
:mkspell en /usr/share/dict/american-english
----

And then moved the `en.utf-8.spl` file to the `spell` subdirectory.

=== Set up in a new machine

Get the files and set symbolic links like the following:

* git clone --recursive git@github.com:suy/configs.git
* ln -s configs/vimrc .vimrc
* ln -s configs/dotvim .vim
* ln -s configs/bashrc .bashrc
* ln -s configs/screenrc .screenrc
* ln -s configs/inputrc .inputrc

Etc.

I automated it a bit by adding a Makefile, so I normally just do:

* make setup-unix

But you can choose which ones to get. I used to have a `setup-windows`, but I no
longer use Windows that much.

The odd setup for gitconfig is because coworkers used to clone my repo and use
it right away without really understanding what were doing, and they had trouble
with the user name and email.

=== Get updates from the depot

* git pull
* git submodule update --init --rebase

=== Update from upstream repositories

* git submodule foreach git pull
* git add dotvim/bundle && git commit

You maybe want to be safe, and do git fetch instead of git pull. Then check the
changes using something like git log master..origin/master.

=== Switch to your fork of a plugin

If you want to provide a patch for a plugin that you are using, and you want to
use that patch right away, you might need to switch the URL of the repository to
the one of your fork. You will have to add your remote to the repository, create
the branch, do the fix, commit and push to a public place. Now you will have to
update the .gitmodules file (since now your commit is in a different URL), and
do git submodule sync to make the .git/config file in sync with .gitmodules.
When you receive updates with git pull, you might need to do also a git
submodule sync before the update, or otherwise it will be impossible for Git to
find the commit in the old repository.

=== Remove a plugin/submodule

Removing a submodule *used to be* a bit tedious with older git versions. Newer
ones seem to be more convenient and a simple `git rm submodule` works does it
all.

Since I end up searching for the recipe online just in case I forget something,
here is it, copied from the Git Wiki:

. Delete the relevant line from the .gitmodules file.
. Delete the relevant section from .git/config.
. Run git rm --cached path_to_submodule (no trailing slash).
. Commit the superproject.
. Delete the now untracked submodule files.

Or, if you install git-extras, the git remove-submodule command is provided.

== Other important tools to install

Externally available, typically:

* https://github.com/sharkdp/fd
* https://github.com/BurntSushi/ripgrep
* https://github.com/Peltoche/lsd

Packaged:

* aptitude
* tmux, tmuxinator
* neovim, neovim-qt
* git
* build-essential, clang, cmake
* icecc, icecc-monitor
* vlc
* silversearcher-ag

== LSP setup

- Install nvim-lspconfig
- Install clangd
- Make clangd symlink to clangd-12
- Add `lua require('lspconfig').clangd.setup{}` to vimrc (or a much more
  involved function that actually makes mappings).

== Modernization and leveraging Neovim

This is like a to-do (which the next section is also about), but more up to date
with current priorities and moving to Neovim.

- Move more things packages from the pathogen setup, if needed. I need to think
  about the "conditional" support of some plugins, that with pathogen I'm able
  to blacklist. Probably the solution is just to put stuff which might be
  loaded or not on the "opt" directory, then load it normally. Don't assume that
  stuff in "start" is the new default.
- Smart input, pairs of characters, etc. Consider smartinput vs lexima vs
  endwise vs who knows what.
- See also :help file-change-detect (:help watch-file in Nvim 0.5).
  (https://github.com/neovim/neovim/issues/1936#issuecomment-964864582).
- I've found that `packagepath` is huge. There are directories for flatpak and
  other stuff that is surely not gonna be ever used. Where are this defaults
  coming from? There are paths that mention KDE and Plasma, so what's the deal
  with that? I think we just need one for the user, one for the system, plus the
  two "after"-suffixed ones.

Further reading:

- https://neovim.discourse.group/t/the-300-line-init-lua-challenge/227/15
- https://github.com/nanotee/nvim-lua-guide

== To do

I still have much to learn, and there is still too much that isn't exactly like
I want it to be. Lately I've been using Vim a lot, so I have many things to
tweak in my vimrc. Here are some notes for self reference:

* Use syntastic properly: learn more about the specific syntax checkers.
* Tweak viminfo and swapfile configuration.
* Reorder and reorganize.
* Test plugins from https://github.com/kana[Kana Natsuno]. He has great things
  there.
* Add (and learn) stuff for nice C++ completion and refactoring (e.g.
  neocomplcache).
* Syntax highlighting for template engines that mix code and markup. Is possible
  to do it in a generic way? What about context-commentstring, context_filetype,
  etc?

Evaluate the following plugins:

* https://github.com/AndrewRadev/deleft.vim
* https://github.com/Shougo/context_filetype.vim
* https://github.com/Shougo/neopairs.vim
* https://github.com/Shougo/vinarise.vim
* https://github.com/andymass/vim-matchup
* https://github.com/bbchung/clighter
* https://github.com/bimlas/vim-high
* https://github.com/chrisbra/Colorizer
* https://github.com/chrisbra/NrrwRgn
* https://github.com/chrisbra/vim-diff-enhanced
* https://github.com/dbmrq/vim-ditto
* https://github.com/fmoralesc/vim-pad
* https://github.com/gorodinskiy/vim-coloresque
* https://github.com/hackhowtofaq/vim-solargraph
* https://github.com/haya14busa/vim-asterisk
* https://github.com/idanarye/vim-vebugger
* https://github.com/jalvesaq/vimcmdline
* https://github.com/jtratner/vim-flavored-markdown
* https://github.com/junegunn/goyo.vim
* https://github.com/justmao945/vim-clang
* https://github.com/kana/vim-operator-siege versus https://github.com/rhysd/vim-operator-surround
* https://github.com/kreskij/Repeatable.vim
* https://github.com/kyuhi/vim-emoji-complete
* https://github.com/lambdalisue/fern.vim
* https://github.com/lambdalisue/vim-gita
* https://github.com/lambdalisue/vim-improve-diff
* https://github.com/libclang-vim/libclang-vim
* https://github.com/lukas-reineke/indent-blankline.nvim
* https://github.com/mhinz/vim-lookup
* https://github.com/nelstrom/vim-textobj-rubyblock
* https://github.com/osyo-manga/vim-brightest
* https://github.com/osyo-manga/vim-operator-blockwise
* https://github.com/osyo-manga/vim-precious
* https://github.com/osyo-manga/vim-watchdogs
* https://github.com/reedes/vim-pencil
* https://github.com/rkitover/vimpager
* https://github.com/rockerBOO/awesome-neovim
* https://github.com/ryanoasis/vim-devicons
* https://github.com/sheerun/vim-polyglot
* https://github.com/stefandtw/quickfix-reflector.vim
* https://github.com/svermeulen/vim-easyclip
* https://github.com/szw/vim-ctrlspace
* https://github.com/tek/vim-textobj-ruby
* https://github.com/tommcdo/vim-express
* https://github.com/tommcdo/vim-ninja-feet versus https://github.com/thinca/vim-textobj-between
* https://github.com/tpope/vim-apathy
* https://github.com/tpope/vim-db
* https://github.com/tpope/vim-git
* https://github.com/tpope/vim-obsession
* https://github.com/tpope/vim-tbone
* https://github.com/vim-jp/vim-cpp
* https://github.com/vim-utils/vim-husk
* https://github.com/w0rp/ale
* https://github.com/wellle/targets.vim

To rethink a bit the fonts choice, or even the deployment to each installation
of the fonts, consider putting in a submodule:

* https://github.com/chrissimpkins/codeface
* https://github.com/chrissimpkins/Hack
* https://github.com/powerline/fonts
* http://input.fontbureau.com/info/

